# Generated by Django 4.1.3 on 2023-08-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('verse', models.CharField(max_length=10000)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
