# Generated by Django 4.1.3 on 2023-09-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
