# Generated by Django 4.1.3 on 2024-03-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianapi', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
