# Generated by Django 4.1.3 on 2025-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianapi', '0003_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='verse',
            field=models.TextField(),
        ),
    ]
