# Generated by Django 4.1.3 on 2025-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianapi', '0004_alter_devotion_content_alter_devotion_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='mailer_lite_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
