# Generated by Django 4.1.3 on 2025-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianapi', '0005_subscriber_mailer_lite_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default='johnson', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mailer_lite_id',
            field=models.IntegerField(null=True),
        ),
    ]
